defaults: &defaults
  ser_api_id: xxxxxxxxxxxxxxxxxxxxxxx
  ser_api_secret_key: xxxxxxxxxxxxxxxxxxxxxxx
  ser_api_path:
    base_path: "http://api.ser.ideas.iii.org.tw/api"
    get_token: "/user/get_token"
    top_article_ptt: "/top_article/ptt"
    top_article_facebook: "/top_article/facebook"
    top_article_forum: "/top_article/forum"
    key_word_search_ptt: "/keyword_search/ptt"
    key_word_search_facebook: "/keyword_search/facebook"
    key_word_search_forum: "/keyword_search/forum"
    key_word_search_news: "/keyword_search/news"
  facebook:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxx
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
