defaults: &defaults
  ser_api:
    id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  facebook:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  apollo:
    server_location: 'http://localhost:20232/'

development:
  <<: *defaults
  apollo:
    server_location: 'http://localhost:20232/'

test:
  <<: *defaults

production:
  <<: *defaults
