defaults: &defaults
  ser_api:
    id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  facebook:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
