defaults: &defaults
  ser_api:
    id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  facebook:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  apollo:
    ws_server: 'http://localhost:20232/'
    api_server: 'http://localhost:4567/'
  devise:
    secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
development:
  <<: *defaults
  apollo:
    server_location: 'http://localhost:20232/'

test:
  <<: *defaults

production:
  <<: *defaults
