defaults: &defaults
  ser_api_id: "31845e22f636e6fe37ba17db4195e312"
  ser_api_secret_key: "e7525005294a4ec974acde6189c3fffc"
  ser_api_path:
    base_path: "http://api.ser.ideas.iii.org.tw/api"
    get_token: "/user/get_token"
    top_article_ptt: "/top_article/ptt"
    top_article_facebook: "/top_article/facebook"
    top_article_forum: "/top_article/forum"
    key_word_search_ptt: "/keyword_search/ptt"
    key_word_search_facebook: "/keyword_search/facebook"
    key_word_search_forum: "/keyword_search/forum"
    key_word_search_news: "/keyword_search/news"
  facebook:
    key: "820757474711654"
    secret: "7bd1bbbc7f73ee5fd60bee1afac67471"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
