# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc18f101ac9b767c64ab63a9d48c25251ca887a958affc660c6da5a0c17ea6899dd48211911a2d757959d10d7e95d1d45989987aef589719ca2abdd5ca43d81

test:
  secret_key_base: 3f33fa87cd8d22f2495475f6eaa733a5ceff3760e0cabca4842eb718deddf0028e4c7a34e91b8970cb42f8ba1587a811f15490f939bc59687db140ebe9c4dd8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
